"""API tests: the contract the frontend is written against."""

from __future__ import annotations

import time

import pytest
from fastapi.testclient import TestClient

from pirao.api.main import app

client = TestClient(app)


def test_meta_describes_every_likelihood_and_prior():
    meta = client.get("/api/meta").json()
    ids = {lik["id"] for lik in meta["likelihoods"]}
    assert {
        "exponential",
        "weibull",
        "lognormal",
        "gamma",
        "bernoulli_geometric",
        "binomial",
    } <= ids
    assert len(meta["priors"]) >= 13

    # The UI builds hyperparameter fields from this, so names and constraints
    # must be present rather than implied.
    gamma = next(p for p in meta["priors"] if p["id"] == "gamma")
    assert [h["name"] for h in gamma["hyperparameters"]] == ["shape", "rate"]
    assert gamma["hyperparameters"][1]["exclusive_minimum"] is True

    # Infinity is not representable in JSON; unbounded reads as null.
    weibull = next(lik for lik in meta["likelihoods"] if lik["id"] == "weibull")
    shape = next(p for p in weibull["parameters"] if p["name"] == "shape")
    assert shape["natural_lower"] == 0.0 and shape["natural_upper"] is None
    assert shape["presets"]

    assert "adapt_delta" in meta["sampler_help"]


def _spec(**overrides):
    spec = {
        "likelihood": "exponential",
        "mission_times": [100.0],
        "params": {
            "rate": {
                "lower": 0.0,
                "prior": {"family": "gamma", "hyper": {"shape": 2.0, "rate": 100.0}},
            }
        },
    }
    spec.update(overrides)
    return spec


def test_validate_spec_returns_effective_bounds_and_a_prior_preview():
    body = client.post("/api/specs/validate", json=_spec()).json()
    assert body["ok"]
    param = body["parameters"][0]
    assert param["effective_lower"] == 0.0
    assert param["effective_upper"] is None
    assert param["preview"]["x"] and param["preview"]["median"] > 0
    assert "GENERATED by pirao" in body["stan_source"]


def test_validate_spec_surfaces_a_silently_truncated_prior():
    spec = _spec()
    spec["params"]["rate"] = {
        "lower": 0.0,
        "upper": 1.0,
        "prior": {"family": "lognormal", "hyper": {"mu": 2.0, "sigma": 1.0}},
    }
    body = client.post("/api/specs/validate", json=spec).json()
    assert body["ok"]
    assert body["parameters"][0]["preview"]["retained_mass"] < 0.1
    assert any("keep only" in w for w in body["warnings"])


def test_validate_spec_reports_an_impossible_model_without_raising():
    spec = _spec()
    spec["params"]["rate"] = {"lower": 0.001, "prior": {"family": "flat", "hyper": {}}}
    body = client.post("/api/specs/validate", json=spec).json()
    assert not body["ok"]
    assert any("lower and an upper bound" in e for e in body["errors"])


def test_data_validation_locates_bad_cells():
    body = client.post(
        "/api/data/validate",
        json={
            "spec": _spec(),
            "rows": [{"time": 10, "failure": 1}, {"time": -1, "failure": 3}],
        },
    ).json()
    assert not body["ok"]
    assert {(e["row"], e["column"]) for e in body["errors"]} == {
        (2, "time"),
        (2, "failure"),
    }


@pytest.mark.parametrize(
    "likelihood",
    ["exponential", "weibull", "lognormal", "gamma", "bernoulli_geometric", "binomial"],
)
def test_templates_download_and_round_trip_through_the_parser(likelihood):
    csv = client.get(f"/api/templates/{likelihood}.csv")
    assert csv.status_code == 200
    assert "attachment" in csv.headers["content-disposition"]

    xlsx = client.get(f"/api/templates/{likelihood}.xlsx")
    assert xlsx.status_code == 200
    assert len(xlsx.content) > 1000

    parsed = client.post(
        "/api/data/parse",
        files={"file": (f"{likelihood}.csv", csv.content, "text/csv")},
    ).json()
    assert parsed["rows"]


def test_an_unreadable_upload_is_explained_not_stack_traced():
    response = client.post(
        "/api/data/parse", files={"file": ("x.csv", b"\x00\x01nonsense", "text/csv")}
    )
    assert response.status_code == 400
    assert (
        "recognised columns" in response.json()["detail"]
        or "could not be read" in response.json()["detail"]
    )


def test_unknown_template_is_a_404():
    assert client.get("/api/templates/nope.csv").status_code == 404


@pytest.mark.slow
def test_a_run_completes_and_exposes_its_artifacts():
    response = client.post(
        "/api/runs",
        json={
            "spec": _spec(),
            "rows": [
                {"device": "A", "time": 120.0, "failure": 1},
                {"device": "B", "time": 300.0, "failure": 0},
                {"device": "C", "time": 45.0, "failure": 1, "relevance": 0.8},
            ],
            "sampler": {
                "chains": 2,
                "iter_warmup": 400,
                "iter_sampling": 400,
                "seed": 7,
            },
        },
    )
    assert response.status_code == 200
    run_id = response.json()["id"]

    deadline = time.time() + 240
    while time.time() < deadline:
        state = client.get(f"/api/runs/{run_id}").json()
        if state["status"] in ("done", "failed", "cancelled"):
            break
        time.sleep(0.5)

    assert state["status"] == "done", state.get("error")
    assert state["seed"] == 7  # the resolved seed is recorded for reproducibility

    names = {row["parameter"] for row in state["summary"]["table"]}
    assert "rate" in names
    assert state["summary"]["reliability_curve"][0]["mission_time"] == 100.0

    # Reliability is reported against the mission it answers for, not against
    # the position it happened to occupy in a Stan vector.
    assert "reliability(t=100 h)" in names
    assert not any(name.startswith("reliability[") for name in names)

    over_time = state["summary"]["reliability_over_time"]
    assert over_time["kind"] == "time"
    assert over_time["mission"] == [100.0]
    assert over_time["points"][0]["x"] == 0.0
    assert over_time["points"][0]["mean"] == pytest.approx(1.0)
    assert over_time["points"][-1]["x"] == pytest.approx(130.0)  # 1.3 x mission
    # Reliability only falls.
    means = [point["mean"] for point in over_time["points"]]
    assert means == sorted(means, reverse=True)

    posterior = client.get(f"/api/runs/{run_id}/posterior").json()
    assert posterior["parameters"] == ["rate"]
    assert len(posterior["columns"]["rate"]) > 100
    # The curve is 121 columns of picture; it belongs in the summary, not in
    # the browser's copy of the draws.
    assert not any("reliability_curve" in name for name in posterior["columns"])

    assert "weibull" not in client.get(f"/api/runs/{run_id}/source").text
    assert client.get(f"/api/runs/{run_id}/draws").status_code == 200
    assert client.get(f"/api/runs/{run_id}/bundle").status_code == 200


def test_a_run_with_bad_data_is_rejected_before_it_starts():
    response = client.post(
        "/api/runs",
        json={"spec": _spec(), "rows": [{"time": -5, "failure": 1}]},
    )
    assert response.status_code == 422
    assert response.json()["detail"]["errors"][0]["column"] == "time"


def test_examples_are_listed_and_served():
    listing = client.get("/api/examples").json()
    assert listing and all("title" in e and "likelihood" in e for e in listing)
    first = client.get(f"/api/examples/{listing[0]['id']}").json()
    assert first["spec"]["likelihood"] == listing[0]["likelihood"]
    assert first["rows"] and first["sampler"]["seed"] is not None
    assert client.get("/api/examples/no-such-example").status_code == 404
