"""Fast tests: no compilation, no sampling.

These cover the rules that decide whether a model is even well posed -- bound
intersection, prior/parameter compatibility, the data contract -- plus the
invariants the compile cache depends on.
"""

from __future__ import annotations

import math

import pytest
from pydantic import ValidationError

from pirao.core.data import (
    CURVE_HEADROOM,
    CURVE_POINTS,
    DataError,
    curve_points,
    template_rows,
    to_stan_data,
    validate_table,
)
from pirao.core.preview import prior_preview, retained_mass
from pirao.core.registry_likelihoods import LIKELIHOODS, get_likelihood
from pirao.core.registry_priors import PRIORS, get_prior
from pirao.core.render import assert_values_are_data, render
from pirao.core.resolve import SpecError, resolve
from pirao.core.spec import ModelSpec, ParamSpec, PriorSpec


def spec_for(likelihood: str, **overrides) -> ModelSpec:
    """A minimal valid spec, so tests only state what they are about."""
    lik = get_likelihood(likelihood)
    defaults = {
        "rate": PriorSpec(family="gamma", hyper={"shape": 2.0, "rate": 0.01}),
        "scale": PriorSpec(family="gamma", hyper={"shape": 2.0, "rate": 0.01}),
        "shape": PriorSpec(family="half_normal", hyper={"sigma": 2.0}),
        "prob": PriorSpec(family="beta", hyper={"a": 1.0, "b": 1.0}),
        "mu": PriorSpec(family="normal", hyper={"mu": 5.0, "sigma": 2.0}),
        "sigma": PriorSpec(family="half_normal", hyper={"sigma": 1.0}),
    }
    params = {
        p.name: ParamSpec(
            lower=0.0 if p.nat_lo == 0.0 else None, prior=defaults[p.name]
        )
        for p in lik.params
    }
    kwargs: dict = {"likelihood": likelihood, "params": params}
    if lik.mission == "time":
        kwargs["mission_times"] = [100.0]
    else:
        kwargs["mission_demands"] = 1
    kwargs.update(overrides)
    return ModelSpec(**kwargs)


# --------------------------------------------------------------------------
# registries


def test_every_likelihood_renders_and_declares_a_consistent_arg_order():
    for lik_id, lik in LIKELIHOODS.items():
        assert set(lik.stan_arg_order) == set(lik.param_names), lik_id
        assert len(lik.stan_arg_order) == len(lik.params), lik_id
        source = render(spec_for(lik_id)).source
        assert "GENERATED by pirao" in source
        for name in lik.param_names:
            assert f" {name};" in source, f"{lik_id} never declares {name}"


def test_weibull_passes_shape_before_scale():
    """Stan's weibull_lpdf is (shape, scale); the reverse still compiles."""
    source = render(spec_for("weibull")).source
    assert "weibull_lpdf(time[i] | shape, scale)" in source
    assert "weibull_lpdf(time[i] | scale, shape)" not in source


def test_gamma_passes_shape_before_rate():
    source = render(spec_for("gamma")).source
    assert "gamma_lpdf(time[i] | shape, rate)" in source


def test_binomial_passes_the_count_first():
    source = render(spec_for("binomial")).source
    assert "binomial_lpmf(failures[i] | n[i], prob)" in source


# --------------------------------------------------------------------------
# the cache / security invariant


@pytest.mark.parametrize("likelihood", sorted(LIKELIHOODS))
def test_hyperparameter_values_never_reach_the_source(likelihood):
    assert_values_are_data(spec_for(likelihood))


def test_changing_a_hyperparameter_reuses_the_same_source():
    a = spec_for("exponential")
    b = spec_for("exponential")
    b.params["rate"].prior.hyper = {"shape": 9.0, "rate": 0.5}
    assert render(a).source == render(b).source


def test_crossing_the_support_edge_does_change_the_source():
    """A bound only alters the program when it cuts into the prior's support."""
    inside = spec_for("exponential")
    inside.params["rate"].upper = 5.0
    assert render(inside).source != render(spec_for("exponential")).source


# --------------------------------------------------------------------------
# bound intersection and compatibility


def test_bounds_are_intersected_with_the_prior_support():
    spec = spec_for("bernoulli_geometric")
    spec.params["prob"] = ParamSpec(
        lower=0.1, prior=PriorSpec(family="beta", hyper={"a": 2.0, "b": 2.0})
    )
    param = resolve(spec).param("prob")
    assert param.lo == 0.1
    assert param.hi == 1.0  # clamped by both the role and the beta support


def test_empty_feasible_set_is_rejected_naming_the_causes():
    spec = spec_for("bernoulli_geometric")
    spec.params["prob"] = ParamSpec(
        lower=1.5, prior=PriorSpec(family="beta", hyper={"a": 1.0, "b": 1.0})
    )
    with pytest.raises(SpecError) as exc:
        resolve(spec)
    message = exc.value.messages[0]
    assert "natural support" in message and "Beta" in message


def test_a_beta_prior_is_refused_on_a_non_probability():
    spec = spec_for("exponential")
    spec.params["rate"] = ParamSpec(
        lower=0.0, prior=PriorSpec(family="beta", hyper={"a": 1.0, "b": 1.0})
    )
    with pytest.raises(SpecError, match="only applies to a probability"):
        resolve(spec)


def test_improper_priors_require_two_finite_bounds():
    spec = spec_for("exponential")
    spec.params["rate"] = ParamSpec(lower=0.001, prior=PriorSpec(family="flat"))
    with pytest.raises(SpecError, match="BOTH a lower and an upper bound"):
        resolve(spec)

    spec.params["rate"] = ParamSpec(
        lower=0.001, upper=10.0, prior=PriorSpec(family="flat")
    )
    resolve(spec)  # now well posed


def test_jeffreys_prior_needs_a_strictly_positive_lower_bound():
    spec = spec_for("exponential")
    spec.params["rate"] = ParamSpec(
        lower=0.0, upper=10.0, prior=PriorSpec(family="jeffreys_scale")
    )
    with pytest.raises(SpecError, match="strictly above zero"):
        resolve(spec)


def test_a_positive_prior_is_refused_on_a_real_valued_parameter():
    spec = spec_for("lognormal")
    spec.params["mu"] = ParamSpec(
        prior=PriorSpec(family="gamma", hyper={"shape": 2.0, "rate": 1.0})
    )
    resolved = resolve(spec).param("mu")
    # gamma's support clamps mu to be non-negative rather than silently
    # allowing a region of zero density.
    assert resolved.lo == 0.0


def test_unknown_and_missing_hyperparameters_are_reported_by_name():
    spec = spec_for("exponential")
    spec.params["rate"] = ParamSpec(
        lower=0.0, prior=PriorSpec(family="gamma", hyper={"shape": 2.0, "wrong": 1.0})
    )
    with pytest.raises(SpecError) as exc:
        resolve(spec)
    joined = " ".join(exc.value.messages)
    assert "wrong" in joined and "rate" in joined


def test_a_negative_scale_hyperparameter_is_rejected_before_stan_sees_it():
    spec = spec_for("exponential")
    spec.params["rate"] = ParamSpec(
        lower=0.0, prior=PriorSpec(family="gamma", hyper={"shape": 2.0, "rate": -1.0})
    )
    with pytest.raises(SpecError, match="must be greater than 0"):
        resolve(spec)


def test_uniform_bounds_fold_into_the_parameter_and_emit_no_distribution():
    spec = spec_for("exponential")
    spec.params["rate"] = ParamSpec(
        prior=PriorSpec(family="uniform", hyper={"a": 0.1, "b": 2.0})
    )
    resolved = resolve(spec)
    param = resolved.param("rate")
    assert (param.lo, param.hi) == (0.1, 2.0)
    source = render(spec).source
    # Named in the header comment for provenance, but never *called*: under
    # `~` a uniform contributes exactly nothing, so emitting one would only
    # mislead.
    assert "uniform(" not in source
    assert "target += -log(rate_ub - rate_lb);" in source


def test_truncated_priors_emit_an_explicit_normaliser():
    spec = spec_for("weibull")
    spec.params["shape"] = ParamSpec(
        lower=0.5,
        upper=6.0,
        prior=PriorSpec(family="normal", hyper={"mu": 2.0, "sigma": 1.0}),
    )
    source = render(spec).source
    assert "log_diff_exp(normal_lcdf(shape_ub" in source
    # never the `~ ... T[]` form, which cannot be combined with `target +=`
    assert "T[" not in source


def test_a_one_sided_truncation_uses_the_cheaper_tail():
    spec = spec_for("weibull")
    spec.params["shape"] = ParamSpec(
        lower=1.0, prior=PriorSpec(family="normal", hyper={"mu": 2.0, "sigma": 1.0})
    )
    source = render(spec).source
    assert "- normal_lccdf(shape_lb" in source
    assert "log_diff_exp" not in source


def test_bounds_warn_when_they_discard_most_of_the_prior():
    spec = spec_for("exponential")
    spec.params["rate"] = ParamSpec(
        lower=0.0,
        upper=1.0,
        prior=PriorSpec(family="lognormal", hyper={"mu": 2.0, "sigma": 1.0}),
    )
    warnings = resolve(spec).warnings
    assert any("keep only" in w for w in warnings)


# --------------------------------------------------------------------------
# spec-level validation


def test_mission_metadata_must_match_the_likelihood():
    with pytest.raises(ValidationError, match="measured in demands"):
        spec_for("bernoulli_geometric", mission_times=[10.0], mission_demands=None)
    with pytest.raises(ValidationError, match="measured in time"):
        spec_for("exponential", mission_times=[], mission_demands=5)


def test_a_missing_parameter_is_named():
    with pytest.raises(ValidationError, match="needs a prior for: scale"):
        ModelSpec(
            likelihood="weibull",
            mission_times=[1.0],
            params={
                "shape": ParamSpec(
                    prior=PriorSpec(family="half_normal", hyper={"sigma": 1.0})
                )
            },
        )


def test_bounds_must_be_ordered():
    with pytest.raises(ValidationError, match="must be below the upper bound"):
        ParamSpec(lower=5.0, upper=1.0, prior=PriorSpec(family="flat"))


# --------------------------------------------------------------------------
# the data contract


def test_relevance_defaults_to_one_and_device_to_the_row_number():
    spec = spec_for("exponential")
    table = validate_table(
        spec, [{"time": 10, "failure": 1}, {"time": 20, "failure": 0}]
    )
    assert [r["relevance"] for r in table.rows] == [1.0, 1.0]
    assert [r["device"] for r in table.rows] == ["1", "2"]


def test_a_missing_required_column_is_reported_once_not_per_row():
    spec = spec_for("exponential")
    with pytest.raises(DataError) as exc:
        validate_table(spec, [{"failure": 1}, {"failure": 0}])
    assert len(exc.value.errors) == 1
    assert exc.value.errors[0].column == "time"


def test_bad_cells_are_located_by_row_and_column():
    spec = spec_for("exponential")
    with pytest.raises(DataError) as exc:
        validate_table(
            spec,
            [
                {"time": 10, "failure": 1},
                {"time": -3, "failure": 2, "relevance": 4},
            ],
        )
    located = {(e.row, e.column) for e in exc.value.errors}
    assert located == {(2, "time"), (2, "failure"), (2, "relevance")}


def test_failure_and_failures_together_are_refused():
    spec = spec_for("binomial")
    with pytest.raises(DataError, match="not both"):
        validate_table(spec, [{"n": 10, "failures": 1, "failure": 1}])


def test_a_failure_needs_at_least_one_demand():
    spec = spec_for("bernoulli_geometric")
    with pytest.raises(DataError, match="cannot fail on demand zero"):
        validate_table(spec, [{"n": 0, "failure": 1}])


def test_more_failures_than_trials_is_refused():
    spec = spec_for("binomial")
    with pytest.raises(DataError, match="cannot exceed"):
        validate_table(spec, [{"n": 5, "failures": 9}])


def test_a_weibull_failure_at_time_zero_depends_on_the_shape_bound():
    """The rule follows from the spec, not from a hard-coded assumption."""
    bounded = spec_for("weibull")
    bounded.params["shape"] = ParamSpec(
        lower=1.0, prior=PriorSpec(family="half_normal", hyper={"sigma": 2.0})
    )
    with pytest.raises(DataError, match="zero probability"):
        validate_table(bounded, [{"time": 0, "failure": 1}])

    unbounded = spec_for("weibull")
    unbounded.params["shape"] = ParamSpec(
        lower=0.0, prior=PriorSpec(family="half_normal", hyper={"sigma": 2.0})
    )
    validate_table(unbounded, [{"time": 0, "failure": 1}])  # allowed


def test_reserved_columns_are_ignored_with_a_note_not_an_error():
    spec = spec_for("exponential")
    table = validate_table(
        spec, [{"time": 10, "failure": 1, "temperature": 350, "subpop": 2}]
    )
    assert table.ignored_columns == ["subpop", "temperature"]
    assert any("ignored" in w for w in table.warnings)


def test_all_censored_data_is_allowed_but_flagged():
    spec = spec_for("exponential")
    table = validate_table(
        spec, [{"time": 10, "failure": 0}, {"time": 20, "failure": 0}]
    )
    assert any("no failure was observed" in w for w in table.warnings)


def test_relevance_weighting_reports_the_effective_sample_size():
    spec = spec_for("exponential")
    table = validate_table(
        spec,
        [
            {"time": 10, "failure": 1, "relevance": 0.5},
            {"time": 20, "failure": 0, "relevance": 0.25},
        ],
    )
    assert any("0.75 effective observations" in w for w in table.warnings)


def test_an_empty_table_is_legal_and_produces_a_prior_only_fit():
    spec = spec_for("exponential")
    table = validate_table(spec, [])
    data = to_stan_data(spec, table)
    assert data["N"] == 0
    assert data["time"] == [] and data["failure"] == []


# --------------------------------------------------------------------------
# the reliability curve's grid


def test_the_curve_runs_past_the_mission_time_by_default():
    spec = spec_for("weibull", mission_times=[500.0])
    grid = curve_points(spec, validate_table(spec, [{"time": 10, "failure": 1}]))

    assert len(grid) == CURVE_POINTS
    assert grid[0] == 0.0
    assert grid[-1] == pytest.approx(500.0 * CURVE_HEADROOM)
    assert grid == sorted(grid)


def test_the_curve_horizon_can_be_set_explicitly():
    spec = spec_for("weibull", mission_times=[500.0], curve_horizon=100.0)
    grid = curve_points(spec, validate_table(spec, []))

    assert grid[-1] == pytest.approx(100.0)


def test_the_data_sets_the_curve_scale_when_no_mission_time_was_given():
    spec = spec_for("weibull", mission_times=[])
    table = validate_table(
        spec, [{"time": 10, "failure": 1}, {"time": 80, "failure": 0}]
    )

    assert curve_points(spec, table)[-1] == pytest.approx(80.0 * CURVE_HEADROOM)


def test_no_mission_and_no_data_means_no_curve_rather_than_an_invented_axis():
    spec = spec_for("weibull", mission_times=[])

    assert curve_points(spec, validate_table(spec, [])) == []


def test_a_demand_curve_is_evaluated_at_whole_demands():
    spec = spec_for("bernoulli_geometric", mission_demands=10)
    grid = curve_points(spec, validate_table(spec, []))

    assert grid == [float(i) for i in range(14)]  # 1.3 * 10, rounded up
    assert all(float(x).is_integer() for x in grid)


def test_a_long_demand_curve_stays_within_the_point_budget():
    spec = spec_for("bernoulli_geometric", mission_demands=100_000)
    grid = curve_points(spec, validate_table(spec, []))

    assert len(grid) <= CURVE_POINTS
    assert all(float(x).is_integer() for x in grid)


def test_the_curve_horizon_must_be_positive():
    with pytest.raises(ValidationError):
        spec_for("weibull", curve_horizon=0.0)
    with pytest.raises(ValidationError):
        spec_for("weibull", curve_horizon=float("inf"))


def test_the_curve_grid_never_reaches_the_generated_source():
    """The horizon is data, so moving it must not invalidate the binary."""
    baseline = render(spec_for("weibull", mission_times=[500.0])).source
    moved = render(
        spec_for("weibull", mission_times=[500.0], curve_horizon=9999.0)
    ).source

    assert baseline == moved


@pytest.mark.parametrize("likelihood", sorted(LIKELIHOODS))
def test_reliability_is_defined_once_and_used_for_both_reports(likelihood):
    """One definition of R(t) per model: the table and the curve share it."""
    source = render(spec_for(likelihood)).source

    assert source.count("real reliability_at(real t") == 1
    assert "reliability_curve[g] = reliability_at(" in source
    assert "reliability_at(mission_time[m]" in source or (
        "reliability_at(mission_demands" in source
    )


# --------------------------------------------------------------------------
# the Stan data contract


@pytest.mark.parametrize("likelihood", sorted(LIKELIHOODS))
def test_the_data_dict_matches_the_generated_data_block(likelihood):
    """Every declared data variable must be supplied, and nothing extra.

    Derived from the generated source rather than maintained by hand -- this is
    the second-easiest place in the project to be silently wrong.
    """
    spec = spec_for(likelihood)
    rendered = render(spec)
    _, examples = template_rows(likelihood)
    table = validate_table(spec, examples)
    data = to_stan_data(spec, table)

    declared: set[str] = set()
    inside = False
    for line in rendered.source.splitlines():
        stripped = line.strip()
        if stripped.startswith("data {"):
            inside = True
            continue
        if inside and stripped == "}":
            break
        if not inside or not stripped or stripped.startswith("//"):
            continue
        name = stripped.split("//")[0].strip().rstrip(";").split()[-1]
        declared.add(name.split("[")[0])

    assert declared, "no data block was parsed"
    assert declared == set(data), (
        f"{likelihood}: declared-but-missing={sorted(declared - set(data))}, "
        f"supplied-but-undeclared={sorted(set(data) - declared)}"
    )


@pytest.mark.parametrize("likelihood", sorted(LIKELIHOODS))
def test_the_shipped_template_is_valid_data_for_its_own_likelihood(likelihood):
    header, rows = template_rows(likelihood)
    assert set(rows[0]) <= set(header)
    validate_table(spec_for(likelihood), rows)


# --------------------------------------------------------------------------
# prior previews


def test_retained_mass_detects_a_badly_truncated_prior():
    lognormal = get_prior("lognormal")
    assert retained_mass(
        lognormal, {"mu": 0.0, "sigma": 1.0}, 0.0, 1.0
    ) == pytest.approx(0.5, abs=1e-3)
    assert retained_mass(
        lognormal, {"mu": -6.0, "sigma": 1.0}, 0.0, 1.0
    ) == pytest.approx(1.0, abs=1e-6)


def test_half_families_on_their_natural_support_lose_no_mass():
    # Emitted as the symmetric density on a parameter bounded at 0, but the
    # prior the user chose is the half one, so [0, inf) keeps all of it.
    for family in ("half_normal", "half_cauchy"):
        assert retained_mass(
            get_prior(family), {"sigma": 2.0}, 0.0, None
        ) == pytest.approx(1.0)
    assert retained_mass(
        get_prior("half_normal"), {"sigma": 1.0}, 0.0, 1.0
    ) == pytest.approx(0.6827, abs=1e-3)


def test_the_preview_describes_the_truncated_prior_not_the_entered_one():
    preview = prior_preview("lognormal", {"mu": 0.0, "sigma": 1.0}, 0.0, 1.0)
    assert preview.retained_mass == pytest.approx(0.5, abs=1e-3)
    assert preview.median < 1.0  # the untruncated median is exactly 1.0
    assert preview.warning and "keep only" in preview.warning


def test_an_improper_family_previews_as_a_warning_until_bounded():
    unbounded = prior_preview("flat", {}, 0.0, None)
    assert not unbounded.is_proper and unbounded.warning

    bounded = prior_preview("flat", {}, 2.0, 6.0)
    assert bounded.median == pytest.approx(4.0)
    assert bounded.pdf and all(math.isclose(p, 0.25) for p in bounded.pdf)


@pytest.mark.parametrize("family", sorted(PRIORS))
def test_every_family_previews_without_raising(family):
    prior = get_prior(family)
    hyper = {h.name: (h.default if h.default else 1.0) for h in prior.hypers}
    if family == "uniform":
        hyper = {"a": 0.0, "b": 1.0}
    lo = 0.1 if prior.supp_lo >= 0 else -5.0
    prior_preview(family, hyper, lo, 5.0)


# --------------------------------------------------------------------------
# examples


def test_every_example_resolves_and_its_data_validates():
    from pirao.core.examples import get_example, list_examples

    listing = list_examples()
    assert len(listing) >= 6
    assert {e["data_kind"] for e in listing} <= {"public", "illustrative"}
    for entry in listing:
        assert entry["title"] and entry["title_pt"] and entry["source"]
        assert entry["note_pt"] and entry["source_pt"]
        example = get_example(entry["id"])
        spec = ModelSpec.model_validate(example["spec"])
        resolved = resolve(spec)
        validate_table(spec, example["rows"], resolved)


def test_prior_density_is_the_truncated_renormalised_prior():
    import numpy as np

    from pirao.core.preview import prior_density

    x = np.linspace(0.0, 1.0, 2001)
    pdf = prior_density("lognormal", {"mu": 0.0, "sigma": 1.0}, 0.0, 1.0, x)
    assert np.trapezoid(pdf, x) == pytest.approx(1.0, abs=2e-3)
    flat = prior_density("flat", {}, 2.0, 4.0, np.array([1.0, 3.0, 5.0]))
    assert list(flat) == [0.0, 0.5, 0.0]
    assert prior_density("flat", {}, 0.0, None, x) is None


def test_kaplan_meier_handles_censoring_and_weights():
    from types import SimpleNamespace

    from pirao.core.results import kaplan_meier

    def fake(rows):
        lik = SimpleNamespace(mission="time")
        return SimpleNamespace(
            resolved=SimpleNamespace(likelihood=lik),
            spec=SimpleNamespace(prior_only=False),
            table=SimpleNamespace(rows=rows),
        )

    rows = [
        {"time": 1.0, "failure": 1, "relevance": 1.0},
        {"time": 2.0, "failure": 0, "relevance": 1.0},
        {"time": 3.0, "failure": 1, "relevance": 1.0},
        {"time": 4.0, "failure": 1, "relevance": 1.0},
    ]
    km = kaplan_meier(fake(rows))
    # 4 at risk, 1 fails -> 3/4; one censored; 2 at risk, 1 fails -> 3/8; then 0.
    assert [s["s"] for s in km["steps"]] == pytest.approx([1.0, 0.75, 0.375, 0.0])
    assert km["censored"] == [{"t": 2.0, "s": 0.75}]
    half = kaplan_meier(fake([dict(r, relevance=0.5) for r in rows]))
    assert [s["s"] for s in half["steps"]] == pytest.approx([1.0, 0.75, 0.375, 0.0])


def test_every_registry_text_has_a_portuguese_translation():
    """A new or reworded English string must come with its Portuguese."""
    from pirao.api.main import get_meta
    from pirao.locales import missing

    meta = get_meta()
    texts = []
    for lik in meta["likelihoods"]:
        texts += [lik["label"], lik["description"]]
        for param in lik["parameters"]:
            texts += [param["label"], param["description"]]
            texts += [preset["label"] for preset in param["presets"]]
    for prior in meta["priors"]:
        texts += [prior["label"], prior["notes"]]
        texts += [hyper["label"] for hyper in prior["hyperparameters"]]
    texts += list(meta["sampler_help"].values())
    assert missing(texts) == []

    pt = get_meta(lang="pt")
    assert pt["likelihoods"][0]["label"] == "Exponencial (taxa de falha constante)"
    assert pt["sampler_help"]["seed"].startswith("Fixa os números")
